# Generated by Django 5.2.5 on 2025-08-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "whatsapp_number",
                    models.CharField(
                        help_text="Enter your WhatsApp number with the country code, e.g., +905XXXXXXXXX",
                        max_length=20,
                    ),
                ),
                (
                    "google_maps_embed_url",
                    models.TextField(
                        blank=True,
                        help_text="Enter the Google Maps embed URL for your location.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Site Settings",
                "verbose_name_plural": "Site Settings",
            },
        ),
    ]
